# Source: jx-build-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-x-controllerbuild
  labels:
    app: jx-build-controller
    chart: jx-build-controller-0.2.7
    release: jx-build-controller
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::776395010460:role/boost-build-ctrl
    meta.helm.sh/release-name: 'jx-build-controller'
  namespace: jx
