apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: matrix
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "338983805704"
    provider: eks
    region: ap-southeast-1
    registry: 338983805704.dkr.ecr.ap-southeast-1.amazonaws.com
  environments:
  - key: dev
    owner: vc7087
    repository: ghub-jx3-eks-vault
  - key: staging
  - key: production
  ingress:
    domain: boostorium.net
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: awsadmin-development@myboost.com.my
      enabled: false
      production: false
  pipelineUser:
    username: vc7087
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-matrix-2021071311514555890000000d
  - name: reports
    url: s3://reports-matrix-20210713115113270300000001
  - name: repository
    url: s3://repository-matrix-2021071311513656700000000b
  terraform: true
  vault:
    aws:
      dynamoDBRegion: ap-southeast-1
      dynamoDBTable: vault-unseal-matrix-N56TLZpy
      kmsKeyId: 52a5ac89-a7cb-4b99-9f7b-696b102fd4f6
      kmsRegion: ap-southeast-1
      s3Bucket: vault-unseal-matrix-20210713115127123400000005
      s3Region: ap-southeast-1
  webhook: lighthouse
