apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        vc7087/bog: true
        vc7087/boost-api-aggregation: true
        vc7087/ghub-jx3-eks-vault: true
        vc7087/php-helloworld: true
        vc7087/spbog: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        vc7087/bog: merge
        vc7087/boost-api-aggregation: merge
        vc7087/ghub-jx3-eks-vault: merge
        vc7087/php-helloworld: merge
        vc7087/spbog: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - vc7087/ghub-jx3-eks-vault
        - vc7087/bog
        - vc7087/boost-api-aggregation
        - vc7087/php-helloworld
        - vc7087/spbog
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - vc7087/ghub-jx3-eks-vault
        - vc7087/bog
        - vc7087/boost-api-aggregation
        - vc7087/php-helloworld
        - vc7087/spbog
      target_url: http://dashboard-jx.boostorium.com
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
